import './global.css';
import { AuthContextProvider } from './(auth)/components/context';
export const metadata = {
  title: 'Welcome to ecommerce',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <body>{children}</body>
      </AuthContextProvider>
    </html>
  );
}
